# ============================================================================
# ANSIBLE INVENTORY - Auto-generated by Terraform
# ============================================================================

[master]
%{ for idx, ip in master_ips ~}
k8s-master-${idx + 1} ansible_host=${ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=~/.ssh/${ssh_key}.pem
%{ endfor ~}

[worker]
%{ for idx, ip in worker_ips ~}
k8s-worker-${idx + 1} ansible_host=${ip} ansible_user=${ssh_user} ansible_ssh_private_key_file=~/.ssh/${ssh_key}.pem
%{ endfor ~}

[k8s_cluster:children]
master
worker

[k8s_cluster:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
